[package]
name = "bevy-game-jam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6.1", default_features = false, features = ["bevy_gilrs", "bevy_winit", "render", "png", "x11", "filesystem_watcher"] }
tiled = { version = "0.9.5", default_features = false }


[profile.dev.package."*"]
opt-level = 3


[profile.release]
strip = "debuginfo"
lto = "fat"
