[package]
name = "bevy-game-jam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
tiled = { version = "0.9.5", default_features = false }
bevy_rapier2d = { version = "0.12.1", features = ["simd-stable", "render"] }


[profile.dev.package."*"]
opt-level = 3
debug = 1


[profile.release]
strip = "debuginfo"
lto = "fat"
debug = 1
